'use client';
import Image from 'next/image';
import {resizeBox} from '@/lib/resize-box';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {useTranslations} from 'next-intl';
import {bounds,canEdit,fonts,snapBox,visible,writingBounds,type Composition,type Element,type Box} from '@/lib/composition';

type Props={value:Composition;selected:string[];snap:boolean;onSelect:(ids:string[])=>void;onChange:(c:Composition)=>void};
function TextContent({element,onChange,editing,onEditing}:{element:Element;onChange:(e:Element)=>void;editing:boolean;onEditing:()=>void}){
 const t=useTranslations('workspace.composer');const cancel=useRef(false);
 return editing?<textarea autoFocus className="composition-editor" aria-label={t('editText')} defaultValue={element.text??''} maxLength={12000} onFocus={()=>{cancel.current=false;}} onBlur={event=>{const text=event.currentTarget.value;if(!cancel.current&&text!==element.text)onChange({...element,text,runs:undefined});onEditing();}} onKeyDown={event=>{event.stopPropagation();if(event.key==='Escape'){cancel.current=true;onEditing();}if((event.metaKey||event.ctrlKey)&&event.key==='Enter')event.currentTarget.blur();}}/>:<div className="composition-text">{element.runs?element.runs.map((run,i)=><span key={i} style={{fontFamily:fonts[run.font],fontWeight:run.bold?700:400,fontStyle:run.italic?'italic':'normal'}}>{run.text}</span>):(element.text??'').split(/(\*\*[^*]+\*\*|\*[^*]+\*)/g).map((s,i)=>s.startsWith('**')?<strong key={i}>{s.slice(2,-2)}</strong>:s.startsWith('*')?<em key={i}>{s.slice(1,-1)}</em>:s)}{!element.text&&<span className="empty-text-hint">{t('text')}</span>}</div>;
}

export function CompositionCanvas({value,selected,snap,onSelect,onChange}:Props){
 const t=useTranslations('workspace.composer');const root=useRef<HTMLDivElement>(null);const [editingId,setEditingId]=useState<string|null>(null);const [heights,setHeights]=useState<Record<string,number>>({});
 const [moving,setMoving]=useState<{ids:string[];dx:number;dy:number;guides:ReturnType<typeof snapBox>['guides']}|null>(null);
 const [resizing,setResizing]=useState<{id:string;box:Box}|null>(null);
 const resize=useRef<{id:string;box:Box;rotation:number;handle:string;x:number;y:number;scale:number}|null>(null);
 const drag=useRef<{x:number;y:number;scale:number;ids:string[];box:Box;others:Box[]}|null>(null);
 useEffect(()=>{const node=root.current;if(!node)return;const observer=new ResizeObserver(()=>{const measured:Record<string,number>={};node.querySelectorAll<HTMLElement>('[data-element-id]').forEach(el=>{if(el.querySelector('.composition-text'))measured[el.dataset.elementId!]=el.offsetHeight;});setHeights(old=>JSON.stringify(old)===JSON.stringify(measured)?old:measured);});node.querySelectorAll('[data-element-id]').forEach(el=>observer.observe(el));return()=>observer.disconnect();},[value.elements]);
 const positions:Record<string,Box>={};let flowY=value.margin;
 for(const e of value.elements){const height=e.kind==='text'?(heights[e.id]??e.height):e.height;positions[e.id]=e.flow?{x:value.margin,y:flowY,width:560-value.margin*2,height}:{x:e.x,y:e.y,width:e.width,height};if(e.flow&&visible(value,e))flowY+=height+16;}
 if(resizing)positions[resizing.id]=resizing.box;
 const activeElement=selected.length===1?value.elements.find(e=>e.id===selected[0]&&canEdit(value,e)&&visible(value,e)&&!e.flow):undefined;
 const resizeDelta=(event:{clientX:number;clientY:number;shiftKey:boolean})=>{const r=resize.current!;return resizeBox(r.box,r.rotation,r.handle,(event.clientX-r.x)/r.scale,(event.clientY-r.y)/r.scale,event.shiftKey);};
 const patch=(element:Element)=>onChange({...value,elements:value.elements.map(e=>e.id===element.id?element:e)});
 const delta=(event:{clientX:number;clientY:number;altKey:boolean})=>{const d=drag.current!;if(Math.hypot(event.clientX-d.x,event.clientY-d.y)<3)return {ids:d.ids,dx:0,dy:0,guides:[]};const raw={...d.box,x:d.box.x+(event.clientX-d.x)/d.scale,y:d.box.y+(event.clientY-d.y)/d.scale};const target=snap&&!event.altKey?snapBox(raw,d.others,value.margin,6/d.scale):{...raw,guides:[]};return {ids:d.ids,dx:target.x-d.box.x,dy:target.y-d.box.y,guides:target.guides};};
 const surface=writingBounds(value);const clip:CSSProperties={clipPath:`inset(${Math.max(0,surface.y)}px ${Math.max(0,560-surface.x-surface.width)}px ${Math.max(0,792-surface.y-surface.height)}px ${Math.max(0,surface.x)}px)`};
 return <div ref={root} className="composition-canvas" data-document-only={value.exportArea==='document'} style={{background:value.background}} onPointerDown={e=>{if(e.target===e.currentTarget)onSelect([]);}}>
 {value.layers.map((layer,index)=><div key={layer.id} className="composition-layer" style={{zIndex:index+1,display:layer.hidden?'none':undefined}} data-layer={layer.id} data-export-hidden={value.exportArea==='document'&&layer.id==='background'}>
 {value.elements.filter(e=>e.layerId===layer.id&&!e.hidden).map(e=>{const box=positions[e.id],active=selected.includes(e.id),editable=canEdit(value,e),motion=moving?.ids.includes(e.id)?moving:null;return <div key={e.id} className="composition-clip" style={e.clip?clip:undefined}><div data-element-id={e.id} data-kind={e.kind} className={`composition-object ${active?'selected':''}`} role="button" tabIndex={0} aria-label={t('select',{name:e.name})} aria-pressed={active}
 style={{left:box.x+(motion?.dx??0),top:box.y+(motion?.dy??0),width:box.width,height:e.kind==='image'?box.height:undefined,minHeight:12,transform:`rotate(${e.rotation}deg)`,opacity:e.opacity,fontFamily:fonts[e.font],fontSize:e.fontSize,color:e.color,textAlign:e.align,lineHeight:1.5,cursor:editable?'move':'default'}}
 onDoubleClick={()=>{if(e.kind==='text'&&editable)setEditingId(e.id);}}
 onPointerDown={event=>{if(event.button!==0||(event.target as HTMLElement).tagName==='TEXTAREA')return;event.stopPropagation();const group=e.group?value.elements.filter(o=>o.group===e.group).map(o=>o.id):[e.id];const ids=event.shiftKey?(active?selected.filter(id=>!group.includes(id)):[...new Set([...selected,...group])]):active?selected:group;onSelect(ids);if(!editable||e.flow||event.shiftKey)return;const movable=value.elements.filter(o=>ids.includes(o.id)&&canEdit(value,o)&&!o.flow);if(!movable.length)return;drag.current={x:event.clientX,y:event.clientY,scale:event.currentTarget.closest('article')!.getBoundingClientRect().width/560,ids:movable.map(o=>o.id),box:bounds(movable.map(o=>positions[o.id])),others:value.elements.filter(o=>!ids.includes(o.id)&&visible(value,o)&&o.id!==value.surfaceId).map(o=>positions[o.id])};event.currentTarget.setPointerCapture(event.pointerId);}}
 onPointerMove={event=>{if(drag.current)setMoving(delta(event));}}
 onPointerUp={event=>{if(!drag.current)return;const move=delta(event);drag.current=null;setMoving(null);if(move.dx||move.dy)onChange({...value,elements:value.elements.map(o=>move.ids.includes(o.id)?{...o,x:Math.max(-560,Math.min(1120,o.x+move.dx)),y:Math.max(-792,Math.min(1584,o.y+move.dy))}:o)});}}
 onPointerCancel={()=>{drag.current=null;setMoving(null);}}
 onKeyDown={event=>{if((event.target as HTMLElement).tagName==='TEXTAREA')return;if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect([e.id]);if(e.kind==='text'&&editable)setEditingId(e.id);}const d=event.shiftKey?10:1;const dirs:Record<string,[number,number]>={ArrowLeft:[-d,0],ArrowRight:[d,0],ArrowUp:[0,-d],ArrowDown:[0,d]};if(dirs[event.key]&&editable&&!e.flow){event.preventDefault();const [dx,dy]=dirs[event.key];const ids=active?selected:[e.id];onChange({...value,elements:value.elements.map(o=>ids.includes(o.id)&&canEdit(value,o)&&!o.flow?{...o,x:Math.max(-560,Math.min(1120,o.x+dx)),y:Math.max(-792,Math.min(1584,o.y+dy))}:o)});}}}>
 {e.kind==='image'?<Image unoptimized fill draggable={false} sizes="560px" alt="" src={e.asset==='uploaded'?e.image!:`/art/${e.asset}.png`} style={{objectFit:'fill',pointerEvents:'none'}}/>:<TextContent element={e} editing={editingId===e.id} onEditing={()=>setEditingId(null)} onChange={patch}/>}
 </div></div>;})}</div>)}
 {activeElement&&!moving&&editingId!==activeElement.id&&<div className="composition-transform" style={{left:positions[activeElement.id].x,top:positions[activeElement.id].y,width:positions[activeElement.id].width,height:positions[activeElement.id].height,transform:`rotate(${activeElement.rotation}deg)`}}>{(activeElement.kind==='image'?['nw','n','ne','e','se','s','sw','w']:['e','w']).map(handle=><button key={handle} type="button" className={`resize-handle handle-${handle}`} aria-label={`${t('resize',{name:activeElement.name})} (${handle})`} onPointerDown={event=>{if(event.button!==0)return;event.stopPropagation();event.preventDefault();resize.current={id:activeElement.id,box:positions[activeElement.id],rotation:activeElement.rotation,handle,x:event.clientX,y:event.clientY,scale:root.current!.getBoundingClientRect().width/560};event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={event=>{if(resize.current)setResizing({id:resize.current.id,box:resizeDelta(event)});}} onPointerUp={event=>{if(!resize.current)return;const box=resizeDelta(event);const id=resize.current.id;resize.current=null;setResizing(null);onChange({...value,elements:value.elements.map(e=>e.id===id?{...e,...box}:e)});}} onPointerCancel={()=>{resize.current=null;setResizing(null);}} onKeyDown={event=>{if(event.key==='Escape'){resize.current=null;setResizing(null);return;}const directions:Record<string,[number,number]>={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(!directions[event.key])return;event.preventDefault();const [dx,dy]=directions[event.key];const box=resizeBox(positions[activeElement.id],activeElement.rotation,handle,dx*(event.shiftKey?10:1),dy*(event.shiftKey?10:1));patch({...activeElement,...box});}}/>)}</div>}
 {moving?.guides.map((guide,i)=><div key={i} className={`snap-guide ${guide.axis}`} style={guide.axis==='x'?{left:guide.position}:{top:guide.position}}/>)}
 </div>;
}
