'use client';
import {useRef,useState} from 'react';
import {ChevronDown,ChevronRight,GripVertical,Eye,EyeOff,Lock,LockOpen,Plus,Trash2,Type,ImageIcon} from 'lucide-react';
import {useTranslations} from 'next-intl';
import type {Composition} from '@/lib/composition';
export function CompositionLayers({value,selected,onSelect,onChange,onInspect}:{value:Composition;selected:string[];onSelect:(ids:string[])=>void;onChange:(c:Composition)=>void;onInspect:()=>void}){
 const t=useTranslations('workspace.composer');const [collapsed,setCollapsed]=useState<string[]>([]);const [target,setTarget]=useState<string|null>(null);const drag=useRef<string|null>(null);const objectDrag=useRef<string|null>(null);
 const move=(id:string,to:string)=>{const list=[...value.layers];const from=list.findIndex(l=>l.id===id),index=list.findIndex(l=>l.id===to);if(from<0||index<0||from===index)return;const [layer]=list.splice(from,1);list.splice(index,0,layer);onChange({...value,layers:list});};
 return <div className="layer-stack"><div className="composer-row"><button type="button" disabled={value.layers.length>=24} onClick={()=>onChange({...value,layers:[...value.layers,{id:crypto.randomUUID(),name:t('newLayer'),hidden:false,locked:false}]})}><Plus size={14}/>{t('addLayer')}</button><button type="button" disabled={!selected.length} onClick={onInspect}>{t('editSelection')}</button></div><p className="art-help">{t('dragLayers')}</p>
 {[...value.layers].reverse().map(layer=>{const objects=value.elements.filter(o=>o.layerId===layer.id).reverse();const closed=collapsed.includes(layer.id);const patch=(p:Partial<typeof layer>)=>onChange({...value,layers:value.layers.map(l=>l.id===layer.id?{...l,...p}:l)});return <section key={layer.id} data-stack-layer={layer.id} className={`stack-section ${target===layer.id?'drop-target':''}`}>
 <div className="stack-heading"><button type="button" className="stack-icon stack-grip" disabled={layer.locked} aria-label={t('dragLayer',{name:layer.name})} onPointerDown={event=>{if(event.button!==0)return;drag.current=layer.id;event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={event=>{if(!drag.current)return;const row=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLElement>('[data-stack-layer]');setTarget(row?.dataset.stackLayer??null);}} onPointerUp={event=>{const row=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLElement>('[data-stack-layer]');if(drag.current&&row?.dataset.stackLayer)move(drag.current,row.dataset.stackLayer);drag.current=null;setTarget(null);}} onPointerCancel={()=>{drag.current=null;setTarget(null);}} onKeyDown={event=>{if(event.key!=='ArrowUp'&&event.key!=='ArrowDown')return;event.preventDefault();const i=value.layers.indexOf(layer)+(event.key==='ArrowUp'?1:-1);if(value.layers[i])move(layer.id,value.layers[i].id);}}><GripVertical size={14}/></button>
 <button type="button" className="stack-icon" aria-expanded={!closed} aria-label={layer.name} onClick={()=>setCollapsed(closed?collapsed.filter(id=>id!==layer.id):[...collapsed,layer.id])}>{closed?<ChevronRight size={14}/>:<ChevronDown size={14}/>}</button>
 <input className="stack-name" aria-label={t('layerName',{name:layer.name})} maxLength={60} value={layer.name} disabled={layer.locked} onChange={event=>{if(event.target.value.trim())patch({name:event.target.value});}}/><small>{objects.length}</small>
 <button type="button" className="stack-icon" aria-label={t('layerVisibility',{name:layer.name})} aria-pressed={!layer.hidden} onClick={()=>patch({hidden:!layer.hidden})}>{layer.hidden?<EyeOff size={14}/>:<Eye size={14}/>}</button>
 <button type="button" className="stack-icon" aria-label={t('layerLock',{name:layer.name})} aria-pressed={layer.locked} onClick={()=>patch({locked:!layer.locked})}>{layer.locked?<Lock size={14}/>:<LockOpen size={14}/>}</button>
 {!objects.length&&value.layers.length>1&&<button type="button" className="stack-icon" disabled={layer.locked} aria-label={t('deleteLayer',{name:layer.name})} onClick={()=>onChange({...value,layers:value.layers.filter(l=>l.id!==layer.id)})}><Trash2 size={13}/></button>}</div>
 {!closed&&objects.map(o=><div className="stack-object-row" data-stack-object={o.id} key={o.id}><button type="button" className="stack-icon stack-grip" disabled={o.locked||layer.locked} aria-label={t('dragObject',{name:o.name})} onPointerDown={event=>{if(event.button!==0)return;objectDrag.current=o.id;event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={event=>{if(!objectDrag.current)return;const row=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLElement>('[data-stack-layer]');setTarget(row?.dataset.stackLayer??null);}} onPointerUp={event=>{const hit=document.elementFromPoint(event.clientX,event.clientY);const layerId=hit?.closest<HTMLElement>('[data-stack-layer]')?.dataset.stackLayer;const targetId=hit?.closest<HTMLElement>('[data-stack-object]')?.dataset.stackObject;if(objectDrag.current&&layerId&&!value.layers.find(l=>l.id===layerId)?.locked&&targetId!==o.id){const elements=value.elements.filter(e=>e.id!==o.id);const index=targetId?(o.layerId===layerId?value.elements.findIndex(e=>e.id===targetId):elements.findIndex(e=>e.id===targetId)+1):elements.length;elements.splice(index<0?elements.length:index,0,{...o,layerId});onChange({...value,elements});}objectDrag.current=null;setTarget(null);}} onPointerCancel={()=>{objectDrag.current=null;setTarget(null);}} onKeyDown={event=>{if(event.key!=='ArrowUp'&&event.key!=='ArrowDown')return;event.preventDefault();const i=objects.indexOf(o)+(event.key==='ArrowUp'?-1:1);if(!objects[i])return;const elements=[...value.elements];const from=elements.indexOf(o),to=elements.indexOf(objects[i]);[elements[from],elements[to]]=[elements[to],elements[from]];onChange({...value,elements});}}><GripVertical size={12}/></button><button type="button" className="stack-object" aria-pressed={selected.includes(o.id)} onClick={event=>onSelect(event.shiftKey||event.metaKey||event.ctrlKey?(selected.includes(o.id)?selected.filter(id=>id!==o.id):[...selected,o.id]):[o.id])} onDoubleClick={onInspect}>{o.kind==='text'?<Type size={13}/>:<ImageIcon size={13}/>}<span>{o.groupName?`${o.groupName} · ${o.name}`:o.name}</span>{o.hidden&&<EyeOff size={12}/ >}{o.locked&&<Lock size={12}/>}</button></div>)}
 </section>;})}</div>;
}
