'use client';
import {useEffect,useRef,useState} from 'react';
import {useTranslations} from 'next-intl';
export type Ink={color:string;opacity:number};
export function InkColor({color,opacity,disabled,onChange,colors}:{color:string;opacity:number;disabled?:boolean;onChange:(ink:Ink)=>void;colors:Ink[]}){
 const t=useTranslations('workspace.composer');const [open,setOpen]=useState(false);const [recent,setRecent]=useState<Ink[]>([]);const root=useRef<HTMLDivElement>(null);const current=useRef({color,opacity});useEffect(()=>{current.current={color,opacity};},[color,opacity]);
 const remember=()=>{try{const saved=JSON.parse(localStorage.getItem('manuscript-recent-inks')??'[]');const valid=Array.isArray(saved)?saved.filter((v:Ink)=>/^#[0-9a-f]{6}$/i.test(v?.color)&&Number.isFinite(v.opacity)&&v.opacity>=0&&v.opacity<=1):[];const next=[current.current,...valid.filter((v:Ink)=>v.color!==current.current.color||v.opacity!==current.current.opacity)].slice(0,12);localStorage.setItem('manuscript-recent-inks',JSON.stringify(next));setRecent(next);}catch{}};
 useEffect(()=>{if(!open)return;const outside=(event:PointerEvent)=>{if(!root.current?.contains(event.target as Node))setOpen(false);};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside);},[open]);
 const channels=[0,1,2].map(i=>parseInt(color.slice(1+i*2,3+i*2),16));
 const palette=(title:string,inks:Ink[])=><div className="ink-palette"><span>{t(title)}</span><div>{inks.map((ink,i)=><button key={i} type="button" aria-label={`${ink.color} · ${Math.round(ink.opacity*100)}%`} title={`${ink.color} · ${Math.round(ink.opacity*100)}%`} style={{background:ink.color,opacity:Math.max(.2,ink.opacity)}} onClick={()=>{current.current=ink;onChange(ink);remember();}}/>)}{!inks.length&&<small>{t('noColors')}</small>}</div></div>;
 return <div ref={root} className="ink-control" onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget))setOpen(false);}} onKeyDown={event=>{if(event.key==='Escape'){event.stopPropagation();setOpen(false);root.current?.querySelector('button')?.focus();}}}>
 <span>{t('color')}</span><button type="button" disabled={disabled} aria-label={t('color')} aria-expanded={open} onClick={()=>{if(!open){try{const saved=JSON.parse(localStorage.getItem('manuscript-recent-inks')??'[]');if(Array.isArray(saved))setRecent(saved.filter((v:Ink)=>/^#[0-9a-f]{6}$/i.test(v?.color)&&Number.isFinite(v.opacity)).slice(0,12));}catch{}}setOpen(!open);}}><i style={{background:color,opacity}}/>{color.toUpperCase()} <small>{Math.round(opacity*100)}%</small></button>
 {open&&<div className="ink-editor" role="group" aria-label={t('color')}>
 {['red','green','blue','opacity'].map((key,i)=><label key={key}><span>{t(key)}</span><input type="range" aria-label={t(key)} min={0} max={i===3?100:255} value={i===3?Math.round(opacity*100):channels[i]} onPointerUp={remember} onKeyUp={remember} onChange={event=>{const n=Number(event.target.value);const next=i===3?{color,opacity:n/100}:{color:'#'+channels.map((v,j)=>(j===i?n:v).toString(16).padStart(2,'0')).join(''),opacity};current.current=next;onChange(next);}}/><input type="number" aria-label={t('channelValue',{name:t(key)})} min={0} max={i===3?100:255} value={i===3?Math.round(opacity*100):channels[i]} onBlur={remember} onChange={event=>{if(!event.target.value)return;const n=Math.max(0,Math.min(i===3?100:255,Math.round(Number(event.target.value))));const next=i===3?{color,opacity:n/100}:{color:'#'+channels.map((v,j)=>(j===i?n:v).toString(16).padStart(2,'0')).join(''),opacity};current.current=next;onChange(next);}}/></label>)}
 {palette('recentColors',recent)}{palette('documentColors',colors.filter((v,i,a)=>a.findIndex(o=>o.color===v.color&&o.opacity===v.opacity)===i))}
 </div>}
 </div>;
}
